- name: Check if Xcode is installed
  command: mdfind -onlyin /Applications "kMDItemCFBundleIdentifier == 'com.apple.dt.Xcode'"
  register: xcode_app
  changed_when: false
  check_mode: no

- name: Register xcode_installed
  set_fact:
    xcode_installed: "{{ xcode_app.stdout.find('Xcode') != -1 }}"

- name: Get Installed Xcode version
  shell: xcodebuild -version | head -n1 | cut -d " " -f 2
  register: xcode_app_output
  when: xcode_installed
  changed_when: false
  check_mode: no

- name: Export Installed Xcode version
  set_fact:
    xcode_installed_version: "{{ xcode_app_output.stdout }}"
  when: xcode_installed

- name: Get Candidate Xcode version
  shell: echo -n "{{ xcode_xip_location }}" | cut -d "_" -f 2 | sed s/'.xip'//g
  register: xcode_path_parse
  changed_when: false
  check_mode: no

- name: Export Candidate Xcode version
  set_fact:
    xcode_target_version: "{{ xcode_path_parse.stdout }}"

- name: Install Xcode
  block:
    - name: check that the xcode archive is valid
      command: >
        pkgutil --check-signature {{ xcode_xip_location }} |
        grep \"Status: signed Apple Software\"

    - name: Clean up existing Xcode installation
      file:
        path: /Applications/Xcode.app
        state: absent

    - name: Install Xcode and prepare
      script: ../library/xcode.sh {{ xcode_build }} {{ xcode_xip_location }}

    - name: Install Rosetta support
      shell: softwareupdate --install-rosetta --agree-to-license
  when: not xcode_installed or xcode_installed_version is version(xcode_target_version, '!=')

- name: Enable Developer Mode
  developer_mode:
    state: enable
  become: true
